TASK_DATA_JSON_FILE: task_data.json
TIMER_DATA_JSON_FILE: timer_data.json

# Port Configuration
server:
  port: 8181

# Database Configuration
spring:
  h2:
    console:
      path: /h2-console
      enabled: false
      settings:
        trace: false
        web-allow-other: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb